using System.Globalization;
using System.Text;
using System.Text.Json;
using sp2rdlGenExtension.Model;

namespace sp2rdlGenExtension.Services;

internal static class ReportingMigrationSqlBuilder
{
    private const string OpenEndedValidTo = "99991231";

    /// <summary>
    /// Builds an idempotent Flyway migration script that seeds Reporting metadata for the supplied report model.
    /// </summary>
    public static string Build(ReportModel model)
    {
        ArgumentNullException.ThrowIfNull(model);
        Validate(model);

        var validFrom = model.ReportingVersionValidFrom!.Value.Date;
        var reportName = model.Name.Trim();
        var reportDescription = model.Description?.Trim() ?? string.Empty;
        var reportPath = model.OutputPath?.Trim() ?? string.Empty;
        var versionLabel = string.IsNullOrWhiteSpace(model.ReportTitle.Text)
            ? reportName
            : model.ReportTitle.Text.Trim();
        versionLabel = Truncate(versionLabel, 50);
        reportDescription = Truncate(reportDescription, 300);
        reportPath = Truncate(reportPath, 300);

        var builder = new StringBuilder();
        builder.AppendLine("-- Generated by sp2rdlGenExtension. Review before applying through Flyway.");
        builder.AppendLine("SET XACT_ABORT ON;");
        builder.AppendLine();
        builder.AppendLine("BEGIN TRANSACTION;");
        builder.AppendLine();
        builder.AppendLine("DECLARE @AuditUser int = 0;");
        builder.AppendLine("DECLARE @Now datetime2(7) = SYSDATETIME();");
        builder.AppendLine($"DECLARE @ReportInternalName varchar(100) = '{EscapeSql(Truncate(reportName, 100))}';");
        builder.AppendLine($"DECLARE @ReportDescription nvarchar(300) = N'{EscapeSql(reportDescription)}';");
        builder.AppendLine($"DECLARE @VersionValidFrom datetime2(7) = CONVERT(datetime2(7), '{validFrom:yyyyMMdd}', 112);");
        builder.AppendLine($"DECLARE @OpenEndedValidTo datetime2(7) = CONVERT(datetime2(7), '{OpenEndedValidTo}', 112);");
        builder.AppendLine("DECLARE @ReportId int;");
        builder.AppendLine("DECLARE @VersionId int;");
        builder.AppendLine("DECLARE @NextVersionNumber int;");
        builder.AppendLine("DECLARE @ParameterDefinitionId int;");
        builder.AppendLine("DECLARE @UiParameterId int;");
        builder.AppendLine("DECLARE @ComponentTypeId int;");
        builder.AppendLine("DECLARE @DependencyUiParameterId int;");
        builder.AppendLine("DECLARE @DependsOnUiParameterId int;");
        builder.AppendLine("DECLARE @CompareOperatorId tinyint;");
        builder.AppendLine();

        AppendReportMerge(builder);
        AppendVersionMerge(builder, versionLabel, reportPath);
        AppendParameters(builder, model.Parameters);

        builder.AppendLine("COMMIT TRANSACTION;");
        return builder.ToString();
    }

    /// <summary>
    /// Builds a Flyway-compatible file name for the generated Reporting metadata migration.
    /// </summary>
    public static string BuildFileName(ReportModel model, DateTime timestamp)
    {
        ArgumentNullException.ThrowIfNull(model);
        var reportName = string.IsNullOrWhiteSpace(model.Name) ? "report" : model.Name.Trim();
        var safeName = new string(reportName.Select(character =>
            char.IsLetterOrDigit(character) ? character : '_').ToArray());
        safeName = string.IsNullOrWhiteSpace(safeName) ? "report" : safeName.Trim('_');
        return $"V{timestamp:yyyyMMddHHmmss}__seed_reporting_{safeName}.sql";
    }

    /// <summary>
    /// Validates the minimum model data required for Reporting metadata script generation.
    /// </summary>
    private static void Validate(ReportModel model)
    {
        if (string.IsNullOrWhiteSpace(model.Name))
        {
            throw new InvalidOperationException("Report name is required for Reporting metadata migration.");
        }

        if (!model.ReportingVersionValidFrom.HasValue)
        {
            throw new InvalidOperationException("Version valid from date is required for Reporting metadata migration.");
        }

        var duplicateParameterNames = model.Parameters
            .Where(parameter => !string.IsNullOrWhiteSpace(parameter.Name))
            .GroupBy(parameter => parameter.Name.Trim(), StringComparer.OrdinalIgnoreCase)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToList();
        if (duplicateParameterNames.Count > 0)
        {
            throw new InvalidOperationException("Duplicate report parameter names are not allowed: " + string.Join(", ", duplicateParameterNames));
        }
    }

    /// <summary>
    /// Appends the Report MERGE and returns the generated ReportId through a variable.
    /// </summary>
    private static void AppendReportMerge(StringBuilder builder)
    {
        builder.AppendLine("MERGE [Reporting].[Report] AS T");
        builder.AppendLine("USING (VALUES (@ReportInternalName, @ReportDescription)) AS S(InternalName, [Description])");
        builder.AppendLine("   ON T.InternalName = S.InternalName");
        builder.AppendLine("WHEN MATCHED THEN");
        builder.AppendLine("    UPDATE SET");
        builder.AppendLine("        [Description] = S.[Description],");
        builder.AppendLine("        IsActive = 1,");
        builder.AppendLine("        LastModifiedBy = @AuditUser,");
        builder.AppendLine("        LastModifiedAt = @Now");
        builder.AppendLine("WHEN NOT MATCHED THEN");
        builder.AppendLine("    INSERT (InternalName, [Description], IsActive, CreatedBy, CreatedAt)");
        builder.AppendLine("    VALUES (S.InternalName, S.[Description], 1, @AuditUser, @Now);");
        builder.AppendLine();
        builder.AppendLine("SELECT @ReportId = Id");
        builder.AppendLine("FROM [Reporting].[Report]");
        builder.AppendLine("WHERE InternalName = @ReportInternalName;");
        builder.AppendLine();
    }

    /// <summary>
    /// Appends idempotent ReportVersion creation/update for the selected ValidFrom date.
    /// </summary>
    private static void AppendVersionMerge(StringBuilder builder, string versionLabel, string reportPath)
    {
        builder.AppendLine("SELECT @VersionId = Id");
        builder.AppendLine("FROM [Reporting].[ReportVersion]");
        builder.AppendLine("WHERE ReportId = @ReportId");
        builder.AppendLine("  AND ValidFrom = @VersionValidFrom;");
        builder.AppendLine();
        builder.AppendLine("IF @VersionId IS NULL");
        builder.AppendLine("BEGIN");
        builder.AppendLine("    SELECT @NextVersionNumber = ISNULL(MAX(Number), 0) + 1");
        builder.AppendLine("    FROM [Reporting].[ReportVersion]");
        builder.AppendLine("    WHERE ReportId = @ReportId;");
        builder.AppendLine();
        builder.AppendLine("    INSERT INTO [Reporting].[ReportVersion]");
        builder.AppendLine("        (ReportId, LanguageId, Number, Code, Label, DescriptionOverride, IsRemote, [Path], EmbedFonts, ValidFrom, ValidTo, CreatedBy, CreatedAt)");
        builder.AppendLine("    VALUES");
        builder.AppendLine($"        (@ReportId, NULL, @NextVersionNumber, CONCAT('v', @NextVersionNumber), N'{EscapeSql(versionLabel)}', NULL, 0, N'{EscapeSql(reportPath)}', 0, @VersionValidFrom, @OpenEndedValidTo, @AuditUser, @Now);");
        builder.AppendLine();
        builder.AppendLine("    SET @VersionId = CONVERT(int, SCOPE_IDENTITY());");
        builder.AppendLine("END");
        builder.AppendLine("ELSE");
        builder.AppendLine("BEGIN");
        builder.AppendLine("    UPDATE [Reporting].[ReportVersion]");
        builder.AppendLine("    SET");
        builder.AppendLine($"        Label = N'{EscapeSql(versionLabel)}',");
        builder.AppendLine($"        [Path] = N'{EscapeSql(reportPath)}',");
        builder.AppendLine("        LastModifiedBy = @AuditUser,");
        builder.AppendLine("        LastModifiedAt = @Now");
        builder.AppendLine("    WHERE Id = @VersionId;");
        builder.AppendLine("END");
        builder.AppendLine();
    }

    /// <summary>
    /// Appends ParameterDefinition, UiParameter, and dependency metadata blocks.
    /// </summary>
    private static void AppendParameters(StringBuilder builder, IReadOnlyList<ReportParameter> parameters)
    {
        var orderedParameters = parameters
            .Where(parameter => !string.IsNullOrWhiteSpace(parameter.Name))
            .OrderBy(parameter => parameter.OrdinalNumber <= 0 ? int.MaxValue : parameter.OrdinalNumber)
            .ThenBy(parameter => parameter.Name, StringComparer.OrdinalIgnoreCase)
            .ToList();

        foreach (var parameter in orderedParameters)
        {
            AppendParameter(builder, parameter);
        }

        foreach (var parameter in orderedParameters)
        {
            AppendDependencies(builder, parameter);
        }
    }

    /// <summary>
    /// Appends MERGE statements for one parameter definition and its report-version UI usage.
    /// </summary>
    private static void AppendParameter(StringBuilder builder, ReportParameter parameter)
    {
        var parameterName = parameter.Name.Trim().TrimStart('@');
        var componentTypeName = MapComponentTypeName(parameter.ControlType);
        var ordinal = parameter.OrdinalNumber <= 0 ? 1 : parameter.OrdinalNumber;
        var label = string.IsNullOrWhiteSpace(parameter.Prompt) ? parameterName : parameter.Prompt.Trim();
        var staticValuesJson = BuildStaticValuesJson(parameter.StaticValidValues);
        var runtimeSettingsJson = BuildRuntimeSettingsJson(parameter.RuntimeSettings);
        var initialValue = parameter.DefaultValueExpression ?? string.Empty;
        var defaultSortOrder = "0";

        builder.AppendLine($"-- Parameter: {parameterName}");
        builder.AppendLine("SET @ParameterDefinitionId = NULL;");
        builder.AppendLine("SET @UiParameterId = NULL;");
        builder.AppendLine("SET @ComponentTypeId = NULL;");
        builder.AppendLine($"SELECT @ComponentTypeId = Id FROM [Reporting].[ComponentType] WHERE [Name] = N'{EscapeSql(componentTypeName)}';");
        builder.AppendLine("IF @ComponentTypeId IS NULL");
        builder.AppendLine($"    THROW 51001, 'Reporting.ComponentType row with Name = {EscapeSql(componentTypeName)} was not found.', 1;");
        builder.AppendLine();
        builder.AppendLine("MERGE [Reporting].[ParameterDefinition] AS T");
        builder.AppendLine($"USING (VALUES (N'{EscapeSql(parameterName)}', N'{EscapeSql(label)}', @ComponentTypeId, {RequiredSqlLiteral(parameter.EntityKey)}, {RequiredSqlLiteral(parameter.ValueFieldTemplate)}, {RequiredSqlLiteral(parameter.DisplayFieldTemplate)}, {SqlLiteral(initialValue)}, {defaultSortOrder}))");
        builder.AppendLine("    AS S([Name], Label, ComponentTypeId, EntityKey, ValueFieldTemplate, DisplayFieldTemplate, InitialValue, DefaultSortOrder)");
        builder.AppendLine("   ON T.[Name] = S.[Name]");
        builder.AppendLine("WHEN MATCHED THEN");
        builder.AppendLine("    UPDATE SET");
        builder.AppendLine("        EntityKey = S.EntityKey,");
        builder.AppendLine("        ValueFieldTemplate = S.ValueFieldTemplate,");
        builder.AppendLine("        DisplayFieldTemplate = S.DisplayFieldTemplate,");
        builder.AppendLine("        LastModifiedBy = @AuditUser,");
        builder.AppendLine("        LastModifiedAt = @Now");
        builder.AppendLine("WHEN NOT MATCHED THEN");
        builder.AppendLine("    INSERT ([Name], Label, ComponentTypeId, EntityKey, ValueFieldTemplate, DisplayFieldTemplate, InitialValue, DefaultSortOrder, CreatedBy, CreatedAt)");
        builder.AppendLine("    VALUES (S.[Name], S.Label, S.ComponentTypeId, S.EntityKey, S.ValueFieldTemplate, S.DisplayFieldTemplate, S.InitialValue, S.DefaultSortOrder, @AuditUser, @Now);");
        builder.AppendLine();
        builder.AppendLine("SELECT @ParameterDefinitionId = Id FROM [Reporting].[ParameterDefinition] WHERE [Name] = " + SqlLiteral(parameterName) + ";");
        builder.AppendLine();
        builder.AppendLine("MERGE [Reporting].[UiParameter] AS T");
        builder.AppendLine("USING (");
        builder.AppendLine("    SELECT");
        builder.AppendLine("        @VersionId AS VersionId,");
        builder.AppendLine("        @ParameterDefinitionId AS ParameterDefinitionId,");
        builder.AppendLine($"        {ordinal} AS CreationOrder,");
        builder.AppendLine($"        {SqlLiteral(initialValue)} AS InitialValueOverride,");
        builder.AppendLine($"        CASE WHEN ISNULL(PD.Label, N'') <> N'{EscapeSql(label)}' THEN N'{EscapeSql(label)}' ELSE NULL END AS LabelOverride,");
        builder.AppendLine("        NULL AS DisplayFieldTemplateOverride,");
        builder.AppendLine($"        {BitLiteral(!parameter.Nullable)} AS IsRequired,");
        builder.AppendLine($"        {BitLiteral(string.IsNullOrWhiteSpace(parameter.BindToDatasetParameterName))} AS IsAdditional,");
        builder.AppendLine("        NULL AS DefaultSortOrderOverride,");
        builder.AppendLine($"        {BitLiteral(parameter.IsVisible)} AS IsVisible,");
        builder.AppendLine($"        {SqlLiteral(staticValuesJson)} AS StaticValues,");
        builder.AppendLine($"        {SqlLiteral(runtimeSettingsJson)} AS RuntimeSettings");
        builder.AppendLine("    FROM [Reporting].[ParameterDefinition] AS PD");
        builder.AppendLine("    WHERE PD.Id = @ParameterDefinitionId");
        builder.AppendLine(") AS S");
        builder.AppendLine("   ON T.VersionId = S.VersionId");
        builder.AppendLine("  AND T.ParameterDefinitionId = S.ParameterDefinitionId");
        builder.AppendLine("WHEN MATCHED THEN");
        builder.AppendLine("    UPDATE SET");
        builder.AppendLine("        CreationOrder = S.CreationOrder,");
        builder.AppendLine("        InitialValueOverride = S.InitialValueOverride,");
        builder.AppendLine("        LabelOverride = S.LabelOverride,");
        builder.AppendLine("        DisplayFieldTemplateOverride = S.DisplayFieldTemplateOverride,");
        builder.AppendLine("        IsRequired = S.IsRequired,");
        builder.AppendLine("        IsAdditional = S.IsAdditional,");
        builder.AppendLine("        DefaultSortOrderOverride = S.DefaultSortOrderOverride,");
        builder.AppendLine("        IsVisible = S.IsVisible,");
        builder.AppendLine("        StaticValues = S.StaticValues,");
        builder.AppendLine("        RuntimeSettings = S.RuntimeSettings,");
        builder.AppendLine("        LastModifiedBy = @AuditUser,");
        builder.AppendLine("        LastModifiedAt = @Now");
        builder.AppendLine("WHEN NOT MATCHED THEN");
        builder.AppendLine("    INSERT (VersionId, ParameterDefinitionId, CreationOrder, InitialValueOverride, LabelOverride, DisplayFieldTemplateOverride, IsRequired, IsAdditional, DefaultSortOrderOverride, IsVisible, StaticValues, RuntimeSettings, CreatedBy, CreatedAt)");
        builder.AppendLine("    VALUES (S.VersionId, S.ParameterDefinitionId, S.CreationOrder, S.InitialValueOverride, S.LabelOverride, S.DisplayFieldTemplateOverride, S.IsRequired, S.IsAdditional, S.DefaultSortOrderOverride, S.IsVisible, S.StaticValues, S.RuntimeSettings, @AuditUser, @Now);");
        builder.AppendLine();
        builder.AppendLine("SELECT @UiParameterId = Id");
        builder.AppendLine("FROM [Reporting].[UiParameter]");
        builder.AppendLine("WHERE VersionId = @VersionId");
        builder.AppendLine("  AND ParameterDefinitionId = @ParameterDefinitionId;");
        builder.AppendLine();
    }

    /// <summary>
    /// Appends dependency MERGE statements for DependsOn and CompareTo parameter relationships.
    /// </summary>
    private static void AppendDependencies(StringBuilder builder, ReportParameter parameter)
    {
        var parameterName = parameter.Name.Trim().TrimStart('@');
        foreach (var dependencyName in ParseDependencyNames(parameter.DependsOnParameterName))
        {
            AppendDependency(builder, parameterName, dependencyName, compareParams: false, compareOperator: null, parameter.DependencyFilterPath);
        }

        if (!string.IsNullOrWhiteSpace(parameter.CompareToParameterName))
        {
            AppendDependency(builder, parameterName, parameter.CompareToParameterName.Trim().TrimStart('@'), compareParams: true, parameter.CompareOperator, null);
        }
    }

    /// <summary>
    /// Appends one UiParameterDependency MERGE statement and leaves CompareOperatorId empty for filter dependencies.
    /// </summary>
    private static void AppendDependency(
        StringBuilder builder,
        string parameterName,
        string dependsOnParameterName,
        bool compareParams,
        string? compareOperator,
        string? dependencyFilterPath)
    {
        if (string.IsNullOrWhiteSpace(dependsOnParameterName))
        {
            return;
        }

        builder.AppendLine($"-- Dependency: {parameterName} -> {dependsOnParameterName}");
        builder.AppendLine("SET @DependencyUiParameterId = NULL;");
        builder.AppendLine("SET @DependsOnUiParameterId = NULL;");
        builder.AppendLine("SET @CompareOperatorId = NULL;");
        builder.AppendLine();
        builder.AppendLine("SELECT @DependencyUiParameterId = UP.Id");
        builder.AppendLine("FROM [Reporting].[UiParameter] AS UP");
        builder.AppendLine("INNER JOIN [Reporting].[ParameterDefinition] AS PD ON PD.Id = UP.ParameterDefinitionId");
        builder.AppendLine("WHERE UP.VersionId = @VersionId");
        builder.AppendLine($"  AND PD.[Name] = N'{EscapeSql(parameterName)}';");
        builder.AppendLine();
        builder.AppendLine("SELECT @DependsOnUiParameterId = UP.Id");
        builder.AppendLine("FROM [Reporting].[UiParameter] AS UP");
        builder.AppendLine("INNER JOIN [Reporting].[ParameterDefinition] AS PD ON PD.Id = UP.ParameterDefinitionId");
        builder.AppendLine("WHERE UP.VersionId = @VersionId");
        builder.AppendLine($"  AND PD.[Name] = N'{EscapeSql(dependsOnParameterName)}';");
        builder.AppendLine();
        builder.AppendLine("IF @DependencyUiParameterId IS NULL OR @DependsOnUiParameterId IS NULL");
        builder.AppendLine($"    THROW 51002, 'UiParameter dependency could not be resolved: {EscapeSql(parameterName)} -> {EscapeSql(dependsOnParameterName)}.', 1;");
        builder.AppendLine();

        if (compareParams)
        {
            var normalizedOperator = string.IsNullOrWhiteSpace(compareOperator) ? ">=" : compareOperator.Trim();
            builder.AppendLine($"SELECT @CompareOperatorId = Id FROM [Reporting].[CompareOperator] WHERE [Name] = N'{EscapeSql(normalizedOperator)}';");
            builder.AppendLine("IF @CompareOperatorId IS NULL");
            builder.AppendLine($"    THROW 51003, 'Reporting.CompareOperator row with Name = {EscapeSql(normalizedOperator)} was not found.', 1;");
            builder.AppendLine();
        }

        builder.AppendLine("MERGE [Reporting].[UiParameterDependency] AS T");
        builder.AppendLine($"USING (VALUES (@DependencyUiParameterId, @DependsOnUiParameterId, {BitLiteral(compareParams)}, @CompareOperatorId, {SqlLiteral(dependencyFilterPath)}))");
        builder.AppendLine("    AS S(UiParameterId, DependsOnUiParameterId, CompareParams, CompareOperatorId, DependencyFilterPath)");
        builder.AppendLine("   ON T.UiParameterId = S.UiParameterId");
        builder.AppendLine("  AND T.DependsOnUiParameterId = S.DependsOnUiParameterId");
        builder.AppendLine("  AND T.CompareParams = S.CompareParams");
        builder.AppendLine("WHEN MATCHED THEN");
        builder.AppendLine("    UPDATE SET");
        builder.AppendLine("        CompareOperatorId = S.CompareOperatorId,");
        builder.AppendLine("        DependencyFilterPath = S.DependencyFilterPath,");
        builder.AppendLine("        LastModifiedBy = @AuditUser,");
        builder.AppendLine("        LastModifiedAt = @Now");
        builder.AppendLine("WHEN NOT MATCHED THEN");
        builder.AppendLine("    INSERT (UiParameterId, DependsOnUiParameterId, CompareParams, CompareOperatorId, DependencyFilterPath, CreatedBy, CreatedAt)");
        builder.AppendLine("    VALUES (S.UiParameterId, S.DependsOnUiParameterId, S.CompareParams, S.CompareOperatorId, S.DependencyFilterPath, @AuditUser, @Now);");
        builder.AppendLine();
    }

    /// <summary>
    /// Maps generator control types to Reporting.ComponentType names.
    /// </summary>
    private static string MapComponentTypeName(ControlType controlType)
        => controlType switch
        {
            ControlType.Boolean => "Checkbox",
            _ => controlType.ToString()
        };

    /// <summary>
    /// Serializes static valid values to the runtime JSON stored on UiParameter.StaticValues.
    /// </summary>
    private static string? BuildStaticValuesJson(IEnumerable<StaticValidValue> values)
    {
        var rows = values
            .Where(value => !string.IsNullOrWhiteSpace(value.Value))
            .Select((value, index) => new StaticValueRow(
                value.Value.Trim(),
                string.IsNullOrWhiteSpace(value.Label) ? value.Value.Trim() : value.Label.Trim(),
                index + 1))
            .ToList();

        return rows.Count == 0
            ? null
            : JsonSerializer.Serialize(rows, new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });
    }

    /// <summary>
    /// Serializes enabled runtime settings to the JSON stored on UiParameter.RuntimeSettings.
    /// </summary>
    private static string? BuildRuntimeSettingsJson(IEnumerable<ParameterValidatorValue> runtimeSettings)
    {
        var rows = runtimeSettings
            .Where(setting => setting.IsEnabled && !string.IsNullOrWhiteSpace(setting.Code))
            .Select((setting, index) => new RuntimeSettingValueRow(
                setting.Code.Trim(),
                string.IsNullOrWhiteSpace(setting.Kind) ? "validation" : setting.Kind.Trim(),
                ConvertRuntimeSettingValue(setting),
                setting.SortOrder > 0 ? setting.SortOrder : index + 1))
            .ToList();

        return rows.Count == 0
            ? null
            : JsonSerializer.Serialize(rows, new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });
    }

    /// <summary>
    /// Converts a runtime setting value string into the JSON type declared by the config.
    /// </summary>
    private static object ConvertRuntimeSettingValue(ParameterValidatorValue setting)
    {
        var value = setting.Value?.Trim() ?? string.Empty;
        return (setting.ValueType ?? string.Empty).Trim().ToLowerInvariant() switch
        {
            "bool" or "boolean" when value is "1" => true,
            "bool" or "boolean" when value is "0" => false,
            "bool" or "boolean" when bool.TryParse(value, out var boolValue) => boolValue,
            "int" or "integer" when int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var intValue) => intValue,
            "decimal" or "number" when decimal.TryParse(value.Replace(',', '.'), NumberStyles.Number, CultureInfo.InvariantCulture, out var decimalValue) => decimalValue,
            _ => value
        };
    }

    /// <summary>
    /// Parses a comma-separated dependency list from the UI grid.
    /// </summary>
    private static IEnumerable<string> ParseDependencyNames(string? value)
        => string.IsNullOrWhiteSpace(value)
            ? []
            : value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(item => item.Trim().TrimStart('@'))
                .Where(item => !string.IsNullOrWhiteSpace(item))
                .Distinct(StringComparer.OrdinalIgnoreCase);

    private static string BitLiteral(bool value)
        => value ? "1" : "0";

    private static string SqlLiteral(string? value)
        => string.IsNullOrWhiteSpace(value) ? "NULL" : $"N'{EscapeSql(value.Trim())}'";

    private static string RequiredSqlLiteral(string? value)
        => $"N'{EscapeSql(value?.Trim() ?? string.Empty)}'";

    private static string EscapeSql(string value)
        => value.Replace("'", "''");

    private static string Truncate(string value, int maxLength)
        => value.Length <= maxLength ? value : value[..maxLength];

    private sealed record StaticValueRow(string ValueKey, string Name, int SortOrder);

    private sealed record RuntimeSettingValueRow(string Code, string Kind, object Value, int SortOrder);
}
