using System.Text;
using sp2rdlGenExtension.Model;

namespace sp2rdlGenExtension.Generation;

internal static class LocalizationSeedSqlBuilder
{
    public static string Build(ReportModel model, IReadOnlyList<LocalizationLabel> labels)
    {
        if (!model.Localization.Enabled || !model.Localization.GenerateDefaultLanguageSeed || labels.Count == 0)
        {
            return string.Empty;
        }

        var builder = new StringBuilder();
        builder.AppendLine("-- Generated by sp2rdlGenExtension. Review translations before deploying to production.");
        builder.AppendLine();

        AppendLanguage(builder, model, labels, model.Localization.DefaultLanguageId, LanguageTemplateValueMode.CopyDefault);
        foreach (var languageId in model.Localization.GenerateLanguageTemplatesFor
            .Where(languageId => languageId > 0 && languageId != model.Localization.DefaultLanguageId)
            .Distinct())
        {
            AppendLanguage(builder, model, labels, languageId, model.Localization.LanguageTemplateValueMode);
        }

        return builder.ToString();
    }

    private static void AppendLanguage(
        StringBuilder builder,
        ReportModel model,
        IReadOnlyList<LocalizationLabel> labels,
        int languageId,
        LanguageTemplateValueMode valueMode)
    {
        var target = QuoteName(model.Localization.TranslationTable.Schema)
            + "." + QuoteName(model.Localization.TranslationTable.Name);
        var skipGeneral = model.Localization.SkipKeysFromGeneralReport
            && model.Localization.GeneralReportId > 0;

        builder.AppendLine($"-- LanguageId = {languageId}");
        if (skipGeneral)
        {
            builder.AppendLine($"-- Skip keys already translated under General ReportId = {model.Localization.GeneralReportId}");
        }

        foreach (var label in labels)
        {
            var value = valueMode switch
            {
                LanguageTemplateValueMode.Empty => string.Empty,
                LanguageTemplateValueMode.TodoPrefix => "TODO: " + label.DefaultValue,
                _ => label.DefaultValue
            };

            builder.AppendLine($"MERGE INTO {target} AS T");
            if (skipGeneral)
            {
                builder.AppendLine("USING (");
                builder.AppendLine($"    SELECT {model.Localization.ReportId} AS ReportId, {languageId} AS LanguageId, '{EscapeSql(label.Key)}' AS [Key], N'{EscapeSql(value)}' AS [Value]");
                builder.AppendLine("    WHERE NOT EXISTS (");
                builder.AppendLine($"        SELECT 1 FROM {target} AS G");
                builder.AppendLine($"        WHERE G.ReportId = {model.Localization.GeneralReportId}");
                builder.AppendLine($"          AND G.LanguageId = {languageId}");
                builder.AppendLine($"          AND G.[Key] = '{EscapeSql(label.Key)}'");
                builder.AppendLine("          AND G.Deleted = 0");
                builder.AppendLine("    )");
                builder.AppendLine(") AS S(ReportId, LanguageId, [Key], [Value])");
            }
            else
            {
                builder.AppendLine($"USING (VALUES ({model.Localization.ReportId}, {languageId}, '{EscapeSql(label.Key)}', N'{EscapeSql(value)}'))");
                builder.AppendLine("    AS S(ReportId, LanguageId, [Key], [Value])");
            }

            builder.AppendLine("    ON T.ReportId = S.ReportId");
            builder.AppendLine("   AND T.LanguageId = S.LanguageId");
            builder.AppendLine("   AND T.[Key] = S.[Key]");
            builder.AppendLine("   AND T.Deleted = 0");
            builder.AppendLine("WHEN MATCHED THEN");
            builder.AppendLine("    UPDATE SET [Value] = S.[Value]");
            builder.AppendLine("WHEN NOT MATCHED THEN");
            builder.AppendLine("    INSERT (ReportId, LanguageId, [Key], [Value], Deleted)");
            builder.AppendLine("    VALUES (S.ReportId, S.LanguageId, S.[Key], S.[Value], 0);");
            builder.AppendLine();
        }
    }

    private static string QuoteName(string value)
        => "[" + (string.IsNullOrWhiteSpace(value) ? "dbo" : value.Trim()).Replace("]", "]]", StringComparison.Ordinal) + "]";

    private static string EscapeSql(string value)
        => value.Replace("'", "''", StringComparison.Ordinal);
}
